#!/bin/bash

if [ "$#" -lt "1" ]; then
	echo "usage: InputConverter <input>"
	exit 1
fi

# find java claspath
DIR=`dirname $0`
CLASSPATH=.
CLASSPATH+=:$DIR/../lib/*
CLASSPATH+=:$DIR/../bin/

CMD="java -cp $CLASSPATH"
exec $CMD test.InputConverter "$@"
